export const allComponents = [
    {
        title: "input",
        image: "https://i.ibb.co.com/VWfYt5Fz/input-text.png",
        url: "/components/input-text",
        groupName: "input",
    },
    {
        title: "textarea",
        image: "https://i.ibb.co.com/jkMNKCrr/textarea.png",
        url: "/components/input-textarea",
        groupName: "input",
    },
    {
        title: "switch",
        image: "https://i.ibb.co.com/cSXTB3zK/switch.png",
        url: "/components/input-switch",
        groupName: "input",
    },
    {
        title: "radio",
        image: "https://i.ibb.co.com/9km4WHSC/radio.png",
        url: "/components/input-radio",
        groupName: "input",
    },
    {
        title: "Number Input",
        image: "https://i.ibb.co.com/S4z4j1sx/number-input.png",
        url: "/components/input-number",
        groupName: "input",
    },
    {
        title: "Checkbox",
        image: "https://i.ibb.co.com/S4WWhhbV/checkbox.png",
        url: "/components/input-checkbox",
        groupName: "input",
    },
    {
        title: "Strong Password",
        image: "https://i.ibb.co.com/pjd3sG1Z/password.png",
        url: "/components/strong-password",
        groupName: "input",
    },
    {
        title: "Input Range",
        image: "https://i.ibb.co.com/FLVrPv1M/slider.png",
        url: "/components/input-range",
        groupName: "input",
    },
    {
        title: "OTP Input",
        image: "https://i.ibb.co.com/R4vRZK9W/otp-input.png",
        url: "/components/otp-input",
        groupName: "input",
    },
    {
        title: "file upload",
        image: "https://i.ibb.co.com/GfN5kgBw/file-upload.png",
        url: "/components/input-file",
        groupName: "input",
    },
    {
        title: "button",
        image: "https://i.ibb.co.com/FLH85qfW/auth-button.png",
        url: "/components/button",
        groupName: "button",
    },
    {
        title: "Auth Button",
        image: "https://i.ibb.co.com/FLH85qfW/auth-button.png",
        url: "/components/auth-buttons",
        groupName: "button",
    },
    {
        title: "Dropdown Button",
        image: "https://i.ibb.co.com/F4SB7GgH/dropdown-button.png",
        url: "/components/dropdown-button",
        groupName: "button",
    },
    {
        title: "chip",
        image: "https://i.ibb.co.com/3yXwxCSM/chip.png",
        url: "/components/chip",
        groupName: "navigation",
    },
    {
        title: "Timer",
        image: "https://i.ibb.co.com/hJK9MbZy/timer.png",
        url: "/components/timer",
        groupName: "navigation",
    },
    {
        title: "Progress Bar",
        image: "https://i.ibb.co.com/gbfcv2m2/progress-bar.png",
        url: "/components/progress-bar",
        groupName: "navigation",
    },
    {
        title: "breadcrumb",
        image: "https://i.ibb.co.com/zTJhP7jM/breadcrumb.png",
        url: "/components/breadcrumb",
        groupName: "navigation",
    },
    {
        title: "Rating",
        image: "https://i.ibb.co.com/V0ksF2b8/star.png",
        url: "/components/rating",
        groupName: "navigation",
    },
    {
        title: "stepper",
        image: "https://i.ibb.co.com/v6rMh7JV/stepper.png",
        url: "/components/stepper",
        groupName: "navigation",
    },
    {
        title: "tab",
        image: "https://i.ibb.co.com/ZqxbVpv/tabs.png",
        url: "/components/tabs",
        groupName: "navigation",
    },
    {
        title: "modal",
        image: "https://i.ibb.co.com/Ps8HWt5g/tabs-1.png",
        url: "/components/modal",
        groupName: "navigation",
    },
    {
        title: "pagination",
        image: "https://i.ibb.co.com/zwYF6Bg/pagination.png",
        url: "/components/pagination",
        groupName: "navigation",
    },
    {
        title: "tooltip",
        image: "https://i.ibb.co.com/mVJJGD4d/tooltip.png",
        url: "/components/tooltip",
        groupName: "data_display",
    },
    {
        title: "badge",
        image: "https://i.ibb.co.com/fVFMJnp0/badge.png",
        url: "/components/badge",
        groupName: "data_display",
    },
    // {
    //     title: "Table",
    //     image: "https://i.ibb.co.com/fGvGZN0s/table.png",
    //     url: "/components/table",
    //     groupName: "data_display",
    // },
    {
        title: "Timeline",
        image: "https://i.ibb.co.com/cKhF8hcZ/timeline.png",
        url: "/components/timeline",
        groupName: "data_display",
    },
    {
        title: "alert message",
        image: "https://i.ibb.co.com/WpjzVT2R/alert-message.png",
        url: "/components/alert-message",
        groupName: "feedback",
    },
    {
        title: "skeleton",
        image: "https://i.ibb.co.com/ZRLBhLxc/skeleton.png",
        url: "/components/skeleton",
        groupName: "feedback",
    },
    // {
    //     title: "Tree Dropdown",
    //     image: "https://i.ibb.co.com/NgytjVwP/tree-dropdown.png",
    //     url: "/components/tree-dropdown",
    //     groupName: "feedback",
    // },
    {
        title: "loader",
        image: "https://i.ibb.co.com/0RWpT608/loading.png",
        url: "/components/loader",
        groupName: "feedback",
    },
    {
        title: "accordion",
        image: "https://i.ibb.co.com/mCjRgVH1/accordion.png",
        url: "/components/according",
        groupName: "surface",
    },
    {
        title: "card",
        image: "https://i.ibb.co.com/Xrr994ZH/card.png",
        url: "/components/cards",
        groupName: "surface",
    },
    {
        title: "Drag & Drop",
        image: "https://i.ibb.co.com/PXJ3885/drag-drop.png",
        url: "/components/drag-and-drop",
        groupName: "surface",
    },
    // {
    //     title: "appbar",
    //     image: "https://i.ibb.co.com/hxL8b1V5/app-bar.png",
    //     url: "/components/appbar",
    //     groupName: "surface",
    // },
    {
        title: "image gallery",
        image: "https://i.ibb.co.com/YBhbHx8R/image-gellery.png",
        url: "/components/image-gallery",
        groupName: "surface",
    },
];
