export const DevContributorsData = [
    {
        name: 'Raihan Uddin Tuhin\n',
        title: 'Web Developer',
        image: 'https://avatars.githubusercontent.com/u/98041657?v=4',
        linkedinLink: '',
        twitterLink: '',
        githubLink: 'https://github.com/Tuhin35',
        website: 'https://portfolio-final-gamma-six.vercel.app/',
        zenuiHero: false,
    },
    {
        name: 'Rahamtullah sheikh',
        title: 'Software Engineer',
        image: 'https://avatars.githubusercontent.com/u/76489436?v=4',
        linkedinLink: 'https://www.linkedin.com/in/rahamtullah-sheikh-792497205/',
        twitterLink: 'https://x.com/Rahamtullah123',
        githubLink: 'https://github.com/rhm856591',
        website: 'https://rahamtullah-sheikh.netlify.app/',
        zenuiHero: false,
    },
    {
        name: 'Danish Kamal',
        title: 'Frontend Developer',
        image: 'https://avatars.githubusercontent.com/u/46997504?v=4',
        linkedinLink: 'https://www.linkedin.com/in/danishzayan/',
        twitterLink: '',
        githubLink: 'https://github.com/danishzayan',
        website: '',
        zenuiHero: true,
    },
    {
        name: 'Eshwar S Devaramane',
        title: 'Software Engineer',
        image: 'https://i.ibb.co.com/WfP5nhm/1712361854052.jpg',
        linkedinLink: 'https://www.linkedin.com/in/eshwar-sdev/',
        twitterLink: '',
        githubLink: 'https://github.com/eshward95/',
        website: 'https://bento.me/e-sdev',
        zenuiHero: false,
    },
    {
        name: 'phuoctaiismee',
        title: 'Web Developer',
        image: 'https://avatars.githubusercontent.com/u/113773744?v=4',
        linkedinLink: '',
        twitterLink: '',
        githubLink: 'https://github.com/phuoctaiismee',
        website: '',
        zenuiHero: false,
    },
    {
        name: 'MD.Asif Ullah',
        title: 'Web Developer',
        image: 'https://i.ibb.co.com/YNSYsPL/122894322.jpg',
        linkedinLink: 'https://www.linkedin.com/in/DevMdAsif',
        twitterLink: 'https://x.com/DevMdAsif',
        githubLink: 'https://github.com/md-asif-ullah',
        website: '',
        zenuiHero: false,
    },
    {
        name: 'Fabian Ajokubi',
        title: 'Frontend Developer',
        image: 'https://i.ibb.co.com/DMxRHBd/1704506313487.jpg',
        linkedinLink: 'https://www.linkedin.com/in/fabiconcept/?originalSubdomain=ng',
        twitterLink: '',
        githubLink: 'https://github.com/fabiconcept',
        website: 'https://fabiconcept.online/',
        zenuiHero: false,
    },
    {
        name: 'Hoang Nguyen',
        title: 'Web Developer',
        image: 'https://i.ibb.co.com/VwfFxF3/67743418.jpg',
        linkedinLink: 'https://www.linkedin.com/in/hoang-nguyen-876a12257/',
        twitterLink: 'https://x.com/akirad836',
        githubLink: 'https://github.com/Zysd836',
        website: '',
        zenuiHero: true,
    },
    {
        name: 'Misbahul Alam',
        title: 'Full-stack Web Developer',
        image: 'https://avatars.githubusercontent.com/u/88716007?v=4',
        linkedinLink: 'https://www.linkedin.com/in/misbahul-alam',
        twitterLink: '',
        githubLink: 'https://github.com/misbahul-alam',
        website: 'https://misbahulalam.vercel.app/',
        zenuiHero: false,
    },
    {
        name: 'Mohammad Shahnwaz',
        title: 'Full-stack Web Developer',
        image: 'https://i.ibb.co.com/pwqnW7M/34994498.jpg',
        linkedinLink: '',
        twitterLink: '',
        githubLink: 'https://github.com/Shahnwazh170',
        website: 'https://shahnwazh170.github.io/',
        zenuiHero: false,
    },
]